services:
  react-ui:
    container_name: react-ui
    build:
      context: ./workspaces/react-ui
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - "./workspaces/react-ui/src:/usr/src/app/src"
    command: "npm start"
  nestjs-api:
    container_name: nestjs-api
    build:
      context: ./workspaces/nestjs-api
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    volumes:
      - ./workspaces/nestjs-api:/svr/app
      - "./scripts/wait.sh:/wait.sh"
      - /svr/app/node_modules
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
